### ISSUE TITLE
TypeError when calling flat_structure

### ISSUE THREAD

**Issue by videlec** [MarkCBell/flipper#2]
With Python3 and the current version from PyPI
```
>>> import flipper
>>> S = flipper.load('S_2_1')
>>> h = S.mapping_class('acBD')
>>> h.flat_structure()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/flipper/kernel/encoding.py", line 792, in flat_structure
    edge_vectors[edges[0]] = flipper.kernel.Vector2(+stable_lamination(edges[0]), +unstable_lamination(edges[0]))
TypeError: bad operand type for unary +: 'RealAlgebraic'
```

**Comment by MarkCBell** [comment]
Thanks for this. This was actually a bug in the realalg package that flipper uses. I've patched it so that its RealAlgebraics have a `__pos__` method, so that +x works. Hopefully this should fix this but you may need to reinstall flipper or run `pip install flipper --upgrade` to upgrade its dependencies.

**Comment by videlec** [comment]
`pip install flipper --upgrade` did not reinstalled realalg but `pip install realalg --upgrade` did. Now works as expected.
