### ISSUE TITLE
flipper should not depend on cypari

### ISSUE THREAD

**Issue by videlec** [MarkCBell/flipper#3]
The fact that `pip install flipper` triggers a `cypari` compilation is extremly annoying. `cypari` is very costly to install (time and space) and requires Cython as well as a C compiler. It is superseeded by `cypari2` and moreover many distributions (Debian/Ubuntu, archlinux, Gentoo, conda, ...) does package `cypari2` (which happens to also be a SageMath dependency).

See also https://github.com/sagemath/cypari2/issues/19

**Comment by MarkCBell** [comment]
Thanks for the suggestion. I've just released flipper 0.14.0 which does not require cypari or cypari2 in order to run. However any function which involves real algebraic numbers (for example computing a dilatation) will be significantly faster if either of those modules are available for import. So it should still be fast if you run flipper within Sage. This is thanks to a new version of realalg.

Hopefully this solves this issue. Let me know what you think.

**Comment by videlec** [comment]
Really nice! I did not ran any tests yet but at least the installation went smoothly. Thanks
